import {z} from "zod";
import {readFile} from "node:fs/promises";
import type {Tool, ToolContext} from "../types.js";
import {displayToolPath, resolveToolPath} from "../shared/paths.js";
import {findMatches, type MatchSpan} from "./strMatch.js";
import {formatDiff} from "./utils.js";
import {normalizeFileText} from "../shared/fileState.js";
import {createFileChange} from "../../fileChanges/index.js";
import {commitFileWrite} from "../shared/fileWrite.js";

const editSchema = z.object({
    old_string: z.string().min(1).describe("Exact text to replace in the current read version."),
    new_string: z.string().describe("Replacement text."),
    replace_all: z.boolean().default(false).describe("Replace every match; requires a full file read."),
}).strict();

const inputSchema = z.object({
    path: z.string().describe("Path of the file to edit."),
    edits: z.array(editSchema).min(1).max(100).describe("Non-overlapping replacements against the same read version. Use one item for a single replacement."),
}).strict();

type Edit = z.infer<typeof editSchema>;
interface Replacement extends MatchSpan {
    newString: string;
    editIndex: number;
}
interface EditValidation {
    originalContent: string;
    normalizedContent: string;
    lineEnding: "\n" | "\r\n";
    replacements: Replacement[];
}

function restoreLineEndings(
    content: string,
    lineEnding: "\n" | "\r\n"
): string {
    return lineEnding === "\r\n" ? content.replace(/\n/g, "\r\n") : content;
}

function readStateMessage(
    path: string,
    reason: "not_read" | "partial_read" | "stale"
): string {
    if (reason === "partial_read") {
        return `read_file did not show all content to edit. Read the range in ${path} containing old_string; replace_all requires reading the entire file first.`;
    }
    if (reason === "stale") {
        return `File ${path} has changed since the last read_file; read it again.`;
    }
    return `Use read_file to read ${path} before editing (to prevent stale writes). Bash cat and other tools do not establish this read record.`;
}

async function validateEdits(
    path: string,
    edits: readonly Edit[],
    ctx: ToolContext
): Promise<{ ok: true; value: EditValidation } | { ok: false; message: string }> {
    let originalContent: string;
    try {
        originalContent = await readFile(path, "utf-8");
    } catch (err) {
        return {
            ok: false,
            message: `Failed to read file: ${err instanceof Error ? err.message : String(err)}`,
        };
    }

    const state = ctx.fileState.check(path, originalContent);
    if (!state.ok) return {ok: false, message: readStateMessage(path, state.reason)};

    const normalizedContent = normalizeFileText(originalContent);
    const replacements: Replacement[] = [];
    for (const [editIndex, edit] of edits.entries()) {
        const fail = (message: string) => ({ok: false as const, message: `Item ${editIndex + 1}: ${message}`});
        const spans = findMatches(normalizedContent, normalizeFileText(edit.old_string));
        if (spans.length === 0) {
            return fail(`In ${path}, old_string was not found in the original version. Verify the target file and exact text with targeted search/read_file; do not retry unchanged. All items must match this file's original contents, not another file or content generated by earlier items.`);
        }
        if (!edit.replace_all && spans.length > 1) {
            return fail(`old_string in ${path} matched ${spans.length} locations, but replace_all=false. Provide unique context or explicitly set replace_all=true.`);
        }
        const observed = ctx.fileState.check(path, originalContent, {
            replaceAll: edit.replace_all,
            ranges: spans.map(span => [
                Buffer.byteLength(normalizedContent.slice(0, span.start)),
                Buffer.byteLength(normalizedContent.slice(0, span.end)),
            ] as const),
        });
        if (!observed.ok) return fail(readStateMessage(path, observed.reason));
        const newString = normalizeFileText(edit.new_string);
        for (const span of spans) replacements.push({...span, newString, editIndex});
    }

    replacements.sort((a, b) => a.start - b.start);
    for (let i = 1; i < replacements.length; i++) {
        const previous = replacements[i - 1]!;
        const current = replacements[i]!;
        if (current.start < previous.end) {
            return {ok: false, message: `Item ${previous.editIndex + 1} overlaps item ${current.editIndex + 1} . Combine them into one unambiguous replacement.`};
        }
    }
    return {
        ok: true,
        value: {
            originalContent,
            normalizedContent,
            lineEnding: originalContent.includes("\r\n") ? "\r\n" : "\n",
            replacements,
        },
    };
}

export const editFileTool: Tool<typeof inputSchema> = {
    name: "edit_file",
    description:
        "Apply one or more exact replacements to a single file using the edits array. All old_string values match the same previously read original version; later edits cannot target text created by earlier edits, and ranges must not overlap. Validate every replacement before one atomic write; any validation failure leaves the file unchanged. Partial reads permit editing only observed content. old_string must match uniquely unless replace_all=true, which requires a full read. Preserve indentation and exclude read_file line-number prefixes. Group known related changes in one call instead of making a model round trip per replacement.",
    parameters: inputSchema,
    isReadOnly: () => false,
    getDefaultApprovalScope: ({path}) => ({kind: "workspace", path}),
    async checkPermissions({path, edits}, ctx) {
        const absPath = resolveToolPath(ctx.cwd, path);
        if (ctx.memoryFiles?.classify(absPath)) {
            return {behavior: "allow" as const};
        }

        const preview = edits.slice(0, 8).map((edit, index) =>
            `Item ${index + 1} (replace_all=${edit.replace_all}):\n${formatDiff(edit.old_string, edit.new_string)}`
        ).join("\n");
        const remaining = edits.length > 8 ? `\nPlus ${edits.length - 8} items; see tool arguments for the full input.` : "";
        return {
            behavior: "ask" as const,
            message: `About to modify ${path}(${edits.length} items):\n ${preview}${remaining}\nRun this command?`,
        };
    },
    execute: async (
        {path, edits: requestedEdits},
        ctx,
        invocation
    ) => {
        const absPath = resolveToolPath(ctx.cwd, path);
        const validation = await validateEdits(absPath, requestedEdits, ctx);
        if (!validation.ok) {
            return {
                content: `Edit failed: ${validation.message} No file was written. Use read_file at the failed location, verify the content, then edit again.`,
                outcome: "failed" as const,
            };
        }

        const {
            originalContent,
            normalizedContent,
            lineEnding,
            replacements,
        } = validation.value;
        const count = replacements.length;

        let normalizedNewContent = normalizedContent;
        for (const span of [...replacements].reverse()) {
            normalizedNewContent = normalizedNewContent.slice(0, span.start) +
                span.newString + normalizedNewContent.slice(span.end);
        }
        const newContent = restoreLineEndings(normalizedNewContent, lineEnding);
        const edits = replacements.map(span => ({start: Buffer.byteLength(normalizedContent.slice(0, span.start)),
            end: Buffer.byteLength(normalizedContent.slice(0, span.end)), insertedBytes: Buffer.byteLength(span.newString)}));

        if (ctx.memoryFiles?.classify(absPath)) {
            ctx.memoryFiles.validateWrite(absPath, newContent);
        }

        if (newContent === originalContent) {
            return `No changes needed for ${path}(content unchanged)`;
        }

        if (ctx.memoryFiles?.classify(absPath)) {
            await ctx.memoryFiles.write(absPath, newContent, originalContent, invocation.toolCallId);
            ctx.fileState.forget(absPath);
            return `Memory note recorded and available for recall; pending consolidation: ${path}. Read the normalized note again before further changes.`;
        }

        const change = createFileChange({
            path: displayToolPath(ctx.cwd, absPath),
            kind: "update",
            oldContent: originalContent,
            newContent,
            replacements: count,
        });

        const {identity} = await commitFileWrite({
            coordinator: ctx.fileCommits,
            signal: ctx.signal,
            path: absPath,
            beforeContent: originalContent,
            afterContent: newContent,
        });
        ctx.fileState.recordWrite({
            identity,
            path: absPath,
            content: newContent,
            beforeContent: originalContent,
            edits,
        });
        const result =
            `Modified ${path} (replaced ${count} matches)`;
        return {
            content: result,
            displayContent: result,
            uiData: {type: "file_change", change},
        };
    },
};
